### ISSUE TITLE
修改首頁碩博班公告連結

### ISSUE THREAD

**Issue by talkamy** [nthu-ee/web-rpage#11]
![image](https://user-images.githubusercontent.com/53547935/63562062-ce60f780-c58e-11e9-99e1-b05d8f3c53d6.png)

上圖那二個連結請幫我改成下面二個連結(名稱不變)
碩士：https://dee.site.nthu.edu.tw/p/412-1175-5151.php
博士：https://dee.site.nthu.edu.tw/p/412-1175-5152.php
而原先的連結網頁如下可以改成不能觀看或空白嗎？
http://dee.site.nthu.edu.tw/p/403-1175-74-1.php?Lang=zh-tw
http://dee.site.nthu.edu.tw/p/403-1175-75-1.php?Lang=zh-tw

**Comment by talkamy** [comment]
再補充碩博班專區裡的碩博士公告也要一起改成
碩士：https://dee.site.nthu.edu.tw/p/412-1175-5151.php
博士：https://dee.site.nthu.edu.tw/p/412-1175-5152.php
![image](https://user-images.githubusercontent.com/53547935/63562267-91493500-c58f-11e9-9034-a90ad20d2de8.png)

**Comment by jfcherng** [comment]
這兩個是不一樣的，你想要的是「資訊分類」現在用的是「所屬的公告模組」。這兩個是分開設定的，因為頁籤模組只能是一堆子模組，所以沒得選，就只能用公告模組，沒有分類模組這種東西。

![image](https://user-images.githubusercontent.com/6594915/63575794-7e4d5980-c5bd-11e9-9c56-b4fdf2b1129f.png)

---

這個可以改成使用資訊分類連結
![image](https://user-images.githubusercontent.com/6594915/63575822-8c9b7580-c5bd-11e9-8c53-17df67e094e6.png)

這邊只能使用模組，也就是現在用的公告模組
![image](https://user-images.githubusercontent.com/6594915/63575856-a1780900-c5bd-11e9-8a32-6511abb0d805.png)

---

請決定打算兩邊使用不同的連結，還是不修改。

**Comment by talkamy** [comment]
不用修改了，謝謝！
