### ISSUE TITLE
首頁跑馬燈畫質較舊版差有辦法調整嗎？

### ISSUE THREAD

**Issue by talkamy** [nthu-ee/web-rpage#12]
![image](https://user-images.githubusercontent.com/53547935/63737233-52c9b800-c8b8-11e9-8f4a-0a9a790797a0.png)
首頁跑馬燈畫質較舊版差有辦法調整嗎？
會是因為圖變大造成的嗎？

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/63739894-8ceb8780-c8c1-11e9-8e6c-8325139b20af.png)

可以在上圖的位置中調整。它是「小圖尺寸」沒錯。

**Comment by jfcherng** [comment]
該跑馬燈的長寬在 1920x1080 的螢幕上是 1134x500

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/63740260-dc7e8300-c8c2-11e9-9575-e8642d7170b2.png)

像這張在跑馬燈上看起來畫質不好是因為原圖本來就沒那麼大張 http://web.ee.nthu.edu.tw/p/406-1175-153865,r2471.php?Lang=zh-tw
