### ISSUE TITLE
https://web.ee.nthu.edu.tw 吃到錯誤的 SSL 憑證？

### ISSUE THREAD

**Issue by jfcherng** [nthu-ee/web-rpage#13]
https://web.ee.nthu.edu.tw

![image](https://user-images.githubusercontent.com/6594915/63740365-49921880-c8c3-11e9-8f20-f68256f38e26.png)

**Comment by talkamy** [comment]
和計中反應過，因為伺服器只能吃一層的萬用憑証，所以除了更換對外的網址( https://dee.site.nthu.edu.tw/ )，沒有其他的辦法

**Comment by jfcherng** [comment]
這麼瞎的嗎。難道只有電機、資訊學院比較特別，用自己的 `web.學系.nthu.edu.tw` 的域名 :confused:
