### ISSUE TITLE
首頁跑馬燈的圖片上面會被截掉？

### ISSUE THREAD

**Issue by talkamy** [nthu-ee/web-rpage#14]
以chrome、firefox來看首頁跑馬燈的圖片上面會被截掉，
![image](https://user-images.githubusercontent.com/53547935/63922939-3b392d80-ca78-11e9-831f-24d70cf6a0f6.png)
但ie不會
![image](https://user-images.githubusercontent.com/53547935/63922826-02995400-ca78-11e9-9329-57e207c4ee74.png)
可以都不截掉嗎？還是說截掉下部？

**Comment by jfcherng** [comment]
IE 單純不支援，設計上我是要求它(瀏覽器)等比例縮放後剪裁的。

不剪裁的話，要麼圖片長寬比例失衡(像IE)，要麼每張圖片大小不同（那麼跑馬燈該如何處理？）。

但是你的那個剪裁是怎麼辦到的... 我看到的是這樣
![image](https://user-images.githubusercontent.com/6594915/63924615-227e4700-ca7b-11e9-89b5-5412f1aea923.png)

**Comment by jfcherng** [comment]
不然就是單純縮放，兩邊都是白邊。我是覺得很醜啦....

![image](https://user-images.githubusercontent.com/6594915/63924807-86087480-ca7b-11e9-96bc-5888cb61fcf7.png)

**Comment by talkamy** [comment]
但單純縮放，二邊留白比頭被切掉好，未來可以固定放資料上去的圖片大小，那應該是什麼？

**Comment by jfcherng** [comment]
頭被切掉的問題我無法重現，亦即，我無法得知為什麼你的跑馬燈這麼窄。

**Comment by talkamy** [comment]
我只是按過ctrl+和-調整畫面大小
之前傳的是用遠端看到的畫面，本機的畫面如下
![image](https://user-images.githubusercontent.com/53547935/63925540-d9c78d80-ca7c-11e9-9b72-b7de9cc2d625.png)

**Comment by jfcherng** [comment]
期望的跑馬燈大小我這邊可以改，看系辦的照片長寬比哪一種比較多。

**Comment by talkamy** [comment]
跑馬燈的新聞都是之前曾琳處理的，還是先依現有的挑比較多的或比較適合的大小，以後就照那個比列

**Comment by jfcherng** [comment]
https://github.com/nthu-ee/web-rpage/commit/bd93fee6f1e4d7cf6cb621fa3d22329a4e72f0dd 我把裁掉的位置改了一下，然後稍微把跑馬燈的高度增加。你 Ctrl+F5 看看這樣行不行。

![image](https://user-images.githubusercontent.com/6594915/63926170-f6b09080-ca7d-11e9-8e0a-2faf440fe3b3.png)

**Comment by talkamy** [comment]
這樣可以，謝謝！
