### ISSUE TITLE
教職員清單中的圖片被切掉(頭的部分)，可以改為切下半部嗎？

### ISSUE THREAD

**Issue by talkamy** [nthu-ee/web-rpage#15]
![image](https://user-images.githubusercontent.com/53547935/64217364-b45cd880-ceef-11e9-8128-56629e657b01.png)
教職員清單中的圖片被切掉(頭的部分)，可以改為切下半部嗎？
即頭完整，身體小一點沒關係

**Comment by jfcherng** [comment]
這是由程式自己切出圖片中「訊息最多」的部分。

例如這張圖 https://i.ee.nthu.edu.tw/100x120,sc,jpeg/http://alumni.ee.nthu.edu.tw/chinese/showphoto.php?ID=yjhsu

其實原圖是 http://alumni.ee.nthu.edu.tw/chinese/showphoto.php?ID=yjhsu

一個比較簡單的解決方法是，我可以把圖片拉高，應該就比較不會切到頭了。

**Comment by jfcherng** [comment]
好，我放放棄「智慧裁切」了。直接縮放裁切，對徐永珍教授的照片特殊對待。

**Comment by talkamy** [comment]
是否從上傳時就直接裁切照片會比較好？

**Comment by jfcherng** [comment]
當然，給使用者自己裁。

**Comment by talkamy** [comment]
那麼照片應該是幾*幾，請幫忙加在電子化管理系統-教職人員管理裡的照片上傳那的說明。

**Comment by jfcherng** [comment]
長：寬 = 5：6

原始圖片的比例大概對了，後期的圖片的 裁切/縮放 可以靠系上的圖片處理服務。

- https://i.ee.nthu.edu.tw/100x120,jpeg/http://alumni.ee.nthu.edu.tw/chinese/showphoto.php?ID=jjliou
- https://i.ee.nthu.edu.tw/50x60,jpeg/http://alumni.ee.nthu.edu.tw/chinese/showphoto.php?ID=jjliou
- https://i.ee.nthu.edu.tw/100x200,jpeg/http://alumni.ee.nthu.edu.tw/chinese/showphoto.php?ID=jjliou

**Comment by jfcherng** [comment]
> 請幫忙加在電子化管理系統-教職人員管理裡的照片上傳那的說明。

OK.

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/64422055-b1234180-d0d5-11e9-9d4b-840cc2adc98f.png)

JJ 的照片已透過 `教職人員管理系統` 替換照片後修正。
