### ISSUE TITLE
首頁圖示連結可讓系辦自行設定嗎？

### ISSUE THREAD

**Issue by talkamy** [nthu-ee/web-rpage#17]
![image](https://user-images.githubusercontent.com/53547935/64397815-1c98ef00-d095-11e9-926a-4a2a09a4ba40.png)
上圖最左邊的連結希望改成依照選擇顯示不同圖示及其對應的連結，
選擇的可能方式：
1.有個網頁可以點選現在要顯示哪一個圖示及其對應的連結
2.有操作手冊：說明如何修改顯示的圖示及其對應的連結

選項：(圖示以前就有了，是否還找的到？如果找不到我再請人做圖給你)
1.碩士班招生：http://web.ee.nthu.edu.tw/p/412-1175-5153.php
2.博士班招生：http://web.ee.nthu.edu.tw/p/412-1175-5154.php
3.大學甄選：http://web.ee.nthu.edu.tw/p/412-1175-5156.php
4.高中生專區：http://highschool.ee.nthu.edu.tw/

**Comment by jfcherng** [comment]
> 1.有個網頁可以點選現在要顯示哪一個圖示及其對應的連結

由於高中生專區、清華電機facebook、誠徵教師，三者放在同一個 row （模組）裡，感覺彈性太低。

> 2.有操作手冊：說明如何修改顯示的圖示及其對應的連結

系辦人員目前沒有編輯「自訂模組」的權限

---

圖片

- 碩博班招生（沒找到單獨的）：http://web.ee.nthu.edu.tw/var/file/175/1175/img/1462/nthu_ee_application-msds-crop.jpg
- 大學甄選：http://web.ee.nthu.edu.tw/var/file/175/1175/img/1462/nthu_ee_application-crop.jpg
- 高中生專區：http://web.ee.nthu.edu.tw/var/file/175/1175/img/1462/557398945.jpg

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/64425106-76bda280-d0dd-11e9-9a6d-a8583e769f5c.png)
