### ISSUE TITLE
系所成員中不同組所中有人員沒有顯示出來

### ISSUE THREAD

**Issue by talkamy** [nthu-ee/web-rpage#18]
![image](https://user-images.githubusercontent.com/53547935/64398857-f4ab8a80-d098-11e9-9a3f-a0069e506287.png)
上圖的5個項目中有"合聘"的老師沒有顯示出來，不過在全體教師中有，
例如：
系統組應該要有白明憲 教授 電機系系統組與動機系合聘
電力組應該要有黃智方 教授 電機系電力組與電子所合聘
電子所應該要有張彌彰 教授 特聘教授
通訊所應該要有林嘉文 教授
光電所李夢麟應該要有 副教授 電機系系統組與光電所合聘

**Comment by jfcherng** [comment]
Done via https://gitlab.com/nthu-ee-website/nthu-ee-iframe/commit/e784d03273ddae3452cccdb3c441d5ec60581cef.
