### ISSUE TITLE
最新消息是自行寫程式做的嗎？

### ISSUE THREAD

**Issue by talkamy** [nthu-ee/web-rpage#19]
![image](https://user-images.githubusercontent.com/53547935/64595337-51ce7580-d3e4-11e9-947a-62e286fba570.png)

上圖是剛剛有設定在最新消息的公告，
但在最新消息裡顯示的時間點一直都顯示最早儲存的資料(中午)，
不會更新為後來的時間(下午)如紅框部分，
目前先設定不顯示在最新消息了，請再幫忙確認是何問題？

**Comment by jfcherng** [comment]
> 最新消息是自行寫程式做的嗎？

是內建的功能

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/64597417-4f6e1a80-d3e8-11e9-85f0-c901d7eacc01.png)
