### ISSUE TITLE
首頁中欄廣告-碩博班圖示連結大小如何調整？

### ISSUE THREAD

**Issue by talkamy** [nthu-ee/web-rpage#20]
![image](https://user-images.githubusercontent.com/53547935/64938792-95682a00-d891-11e9-981d-d2170c7d881a.png)
紅框中的碩博士班招生原圖像素大小滿大的，但放上去後變的很小，應該到哪裡改呢？

**Comment by jfcherng** [comment]
你用到縮圖了

![Snipaste_2019-09-16_15-09-15](https://user-images.githubusercontent.com/6594915/64939562-f7299380-d893-11e9-86ff-0a3b506d0094.png)

**Comment by talkamy** [comment]
我豬頭了，謝謝！
