### ISSUE TITLE
榮譽成就可以公告資訊的權限？

### ISSUE THREAD

**Issue by talkamy** [nthu-ee/web-rpage#21]
有個帳號ltye之前都可以公告榮譽成就，但現在不行了，請幫忙確認問題，謝謝！

**Comment by jfcherng** [comment]
不懂什麼意思。我開了一個和系辦人員同等權限的帳號測試是可以的。

![image](https://user-images.githubusercontent.com/6594915/65261034-f9ad1700-db39-11e9-930a-6f648f9b7474.png)
![image](https://user-images.githubusercontent.com/6594915/65261172-38db6800-db3a-11e9-9b6d-25ab8e216964.png)

**Comment by talkamy** [comment]
但那個ltye的帳號就是只看的到一個表單模組，看不到其他的模組，但在舊版時她可以用公告模組，若權限設定沒問題，我明早再叫律廷重新登入試一次。

Jack Cherng <notifications@github.com>於 2019年9月20日 週五，上午12:02寫道：

**Comment by jfcherng** [comment]
> 但那個ltye的帳號就是只看的到一個表單模組，看不到其他的模組

這是兩件不同的事情唷。

如果他只是要把某篇文章加入 "榮譽成就" 的公告裡，他並不需要擁有「修改公告模組」的權限。目前系辦人員確實沒有「修改公告模組」的權限。

「修改公告模組」的權限也不是單純用來「將某篇文章加入某個公告」。

---

已給系辦人員「修改公告模組」的權限。

**Comment by talkamy** [comment]
她今天可以用了

Jack Cherng <notifications@github.com> 於 2019年9月20日 週五 上午12:15寫道：
