### ISSUE TITLE
版面修改2

### ISSUE THREAD

**Issue by talkamy** [nthu-ee/web-rpage#4]
版面要再改一下，如下說明(做成像下圖的樣子)：

- [x] 將大學部專區那一欄的分類清單都往下移，以另一列的方式放，分3欄：順序：大學部專區、高中生專區、碩博班專區…(剩下不用改順序)

- [x] 不顯示大學甄選入選那個圖示鈕
- [x] 跑馬燈到各項公告那個區塊應該會變成與研究發展那列切齊
- [x] 深紫色連結列中的”各組研究發展”刪掉”各組”2字
- [x] 將深紫色連結列中的網頁郵件、電子化管理系統移到”其他”這個分類項按鈕中，順序：電子化管理系統、網頁郵件、電機系計算機中心…(剩下不用改順序)
- [x] ”其他”這個分類項按鈕，”其他”這分類名稱改為相關系統及表單
- [x] 高中生專區分類按鈕中的”高中生專區”連結名稱改為給高中生的訊息移到那分類的第1個、刪除”科普園地”
![image](https://user-images.githubusercontent.com/53547935/62279605-0340c980-b47d-11e9-91d6-94fa735c1f51.png)

**Comment by jfcherng** [comment]
> 將大學部專區那一欄的分類清單都往下移，以另一列的方式放，分3欄：順序：大學部專區、高中生專區、碩博班專區…(剩下不用改順序)

  手機的選單也會變成在下面唷

---

- 一般頁面的排版怎麼辦？

  例如 http://dee.site.nthu.edu.tw/p/405-1175-28314,c3091.php

  選單也都移到最下面？

- 首頁的頁籤模組在哪裡？

![image](https://user-images.githubusercontent.com/6594915/62295461-af93a780-b49f-11e9-9720-dd910ee70f5f.png)

**Comment by talkamy** [comment]
1.好的，手機的選單要在下面。
2.一般頁面的排版，如果可以的話
![image](https://user-images.githubusercontent.com/53547935/62336246-04680a00-b502-11e9-8c4a-bc93456e3d0c.png)
3.首頁的頁籤模組在跑馬燈和分類選單之間，如下圖示意，顯示筆數先不做更動：
![image](https://user-images.githubusercontent.com/53547935/62336273-295c7d00-b502-11e9-8ff9-38a3e8bfa65f.png)

**Comment by jfcherng** [comment]
Done.
