### ISSUE TITLE
調整連結及問題

### ISSUE THREAD

**Issue by talkamy** [nthu-ee/web-rpage#6]
- [x] 在分類清單的大學部專區加上幾個連結(原先的後移)：實作專題競賽、暑期實習、學習護照、選課專區，這幾項加入後電腦的畫面應該會比其他項都長，若可以調整成如下圖

![image](https://user-images.githubusercontent.com/53547935/62588151-4a084680-b8f7-11e9-8499-8c5bb748fbb9.png)

- [x] 在分類清單的系友專區加上連結：系友會(放在第2個，把facebook移到第1個、校友問卷放最後一個)
- [x] 把新創營連結改成誠徵教師(http://web.ee.nthu.edu.tw/files/13-1030-37905.php?Lang=zh-tw)
![image](https://user-images.githubusercontent.com/53547935/62587920-766f9300-b8f6-11e9-9ac6-d2b00f003d04.png)

- [x] 跑馬燈點更多新聞後開啟的網頁( http://dee.site.nthu.edu.tw/p/403-1175-2471-1.php?Lang=zh-tw )，滑鼠移過去後字會不見
![image](https://user-images.githubusercontent.com/53547935/62587833-31e3f780-b8f6-11e9-9dce-1e05cff5d1a9.png)

**Comment by jfcherng** [comment]
> 跑馬燈點更多新聞後開啟的網頁( http://dee.site.nthu.edu.tw/p/403-1175-2471-1.php?Lang=zh-tw )，滑鼠移過去後字會不見


Done by 0aed691887eb987b8d8571452b78ae58c9e3aee3.

> ![image](https://user-images.githubusercontent.com/6594915/62589610-5d69e080-b8fc-11e9-918c-191ef062f81f.png)

可以改用三欄式，但只有首頁能用，不過目前底部選單也只存在於首頁中。

其他頁面 RPage 只提供調整 欄數 ，不提供調整 列數 ，此排版要求兩者同時都能調整。
