### ISSUE TITLE
英文版系網頁

### ISSUE THREAD

**Issue by jfcherng** [nthu-ee/web-rpage#7]

**Comment by jfcherng** [comment]
@talkamy 已經完成囉。看看還有沒有哪邊需要修改的。

- 新版英文網頁： http://dee.site.nthu.edu.tw/index.php?Lang=en
- 舊版英文網頁： http://web.ee.nthu.edu.tw/bin/home.php?Lang=en

**Comment by talkamy** [comment]
- 請再增加一個連結，顏色和左側相同即可：Faculty Openings
![image](https://user-images.githubusercontent.com/53547935/63662854-a1ad1a00-c7f2-11e9-927c-02bb60bb05e2.png)

- 中文版首頁最下方的專區分類的項目底色跑掉了，請改回紫色。
![image](https://user-images.githubusercontent.com/53547935/63663051-6eb75600-c7f3-11e9-91fe-caaef732d1fb.png)

**Comment by jfcherng** [comment]
@talkamy ok.

**Comment by talkamy** [comment]
![image](https://user-images.githubusercontent.com/53547935/63736075-7d197680-c8b4-11e9-800d-31caaed61ffe.png)

上面連結請改成http://dee.web.nthu.edu.tw/files/13-1030-49994.php?Lang=en
是2019年的
![image](https://user-images.githubusercontent.com/53547935/63736112-97ebeb00-c8b4-11e9-86cf-d29d225fe51d.png)

**Comment by jfcherng** [comment]
@talkamy Ok. 新網頁是這篇 http://dee.site.nthu.edu.tw/p/406-1175-49994,r7540.php?Lang=en

**Comment by jfcherng** [comment]
已經正式切過去用新網頁了嗎 :+1:
