### ISSUE TITLE
調整專區順序

### ISSUE THREAD

**Issue by talkamy** [nthu-ee/web-rpage#9]
![image](https://user-images.githubusercontent.com/53547935/63137212-cd1c5180-c007-11e9-80ed-b29e95699c61.png)
若以手機觀看的順序：大學部專區、碩博班專區、高中生專區、系友專區、影音專區

**Comment by talkamy** [comment]
若無法就讓大學部專區和碩博班專區在最前面二個就好，其他沒關係

**Comment by jfcherng** [comment]
就這兩種選一種吧

---

![image](https://user-images.githubusercontent.com/6594915/63139324-79623600-c010-11e9-849b-d2f37f452b2d.png)
![image](https://user-images.githubusercontent.com/6594915/63139367-a878a780-c010-11e9-9fc6-487dd6e754b8.png)

---


![image](https://user-images.githubusercontent.com/6594915/63139479-06a58a80-c011-11e9-8591-969010dc5678.png)
![image](https://user-images.githubusercontent.com/6594915/63139459-fb525f00-c010-11e9-98ab-a4c594316145.png)

**Comment by talkamy** [comment]
好

Jack Cherng <notifications@github.com>於 2019年8月16日 週五，上午10:28寫道：
